# config.yaml

log_directory: 'micrawler/log'
log_file_prefix: 'data.log'
null_log_file_prefix: 'null_vide'
log_max_bytes: 5242880  # 5 MB
log_backup_count: 2

database:
  host: 'localhost'
  user: 'root'
  password: '123456'
  name: 'downloaded_videos'

elasticsearch:
  host: 'http://localhost:32774/'
  port: 9200
  index: 'articles'
  doc_type: 'article'
  username: 'elastic'
  password: '*EeGyWQGLKOxX=h00V5V'

crawler:
  li_default_url: 'https://hanime1.me/search?genre=%E8%A3%8F%E7%95%AA'
  motion_default_url_2d: 'https://hanime1.me/search?genre=Motion+Anime'
  motion_default_url_3d: 'https://hanime1.me/search?genre=3D%E5%8B%95%E7%95%AB'
  start_page: 1
  max_retries: 10
  download_path: 'E:/vide'

program_info:
  name: 'Hanime Crawler'
  version: '1.0.0'
  author: 'S^^K'
